name       : bamf
version    : 0.5.3
release    : 7
source     :
    - https://launchpad.net/bamf/0.5/0.5.3/+download/bamf-0.5.3.tar.gz : 340d7b5a463afcd33135ae73a7e4cf6a93a4daaf6f72b70abc09dc66d18a3b14
clang      : no
license    : GPL-3.0
component  : desktop.library
summary    : BAMF Application Matching Framework
description: |
    BAMF Application Matching Framework
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -Wno-error=deprecated-declarations"
    %configure --disable-static --disable-webapps
build      : |
    %make
install    : |
    %make_install
