name       : bamf
version    : 0.5.1
release    : 5
source     :
    - https://launchpad.net/bamf/0.5/0.5.1/+download/bamf-0.5.1.tar.gz : fb65e6d0d7330f06626e43b0f3828bdeb5678d69133396e770a8781b9988fd16
clang      : no
license    : GPL-3.0
summary    : BAMF Application Matching Framework
description: |
    BAMF Application Matching Framework
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(x11)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
