name       : bamf
version    : 0.5.5
release    : 14
source     :
    - https://launchpad.net/bamf/0.5/0.5.5/+download/bamf-0.5.5.tar.xz : 10e642adf5169d46e32b113346bebdad437cddd1ddbd45d16c640cf60cabf5da
clang      : no
license    : GPL-3.0-or-later
component  : desktop.library
summary    : BAMF Application Matching Framework
description: |
    BAMF Application Matching Framework
builddeps  :
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libwnck-3.0)
    - gnome-common
    - gtk-doc
    - python-lxml
    - vala
setup      : |
    %autogen --disable-static --disable-webapps
build      : |
    %make
install    : |
    %make_install
