name       : bamf
version    : 0.5.4
release    : 10
source     :
    - https://launchpad.net/bamf/0.5/0.5.4/+download/bamf-0.5.4.tar.gz : 5bb87a5bf46ab1fc9a229a851c0ee4f610d943716a7c83d318f6a8f50d76beb3
clang      : no
license    : GPL-3.0-or-later
component  : desktop.library
summary    : BAMF Application Matching Framework
description: |
    BAMF Application Matching Framework
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -Wno-error=deprecated-declarations"
    %configure --disable-static --disable-webapps
build      : |
    %make
install    : |
    %make_install
